<?php

/* 
 * Copyright (C) 2014 Joe Nilson <joenilson@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<script>
function deployCombos(comboField,comboValue){
    var combo = form<?=$this->panelId;?>.getForm().findField(comboField);
    var store = combo.store;
    store.on("load", function(store, records, state, operation, opts) {
        combo.setValue(comboValue);
    });
}
function fnOProcess(button, opt, obj) {
    var values = button.up('form').getForm().getValues();
    var offices = values['officesCombo'];
    var dependants = values['dependantCombo'];
    var ageBeginDependant = values['age_begin'];
    var ageEndDependant = values['age_end'];
    gridStore<?= $this->panelId; ?>.load({ params: { module: 'master', offices: offices, dependant_type: dependants, age_begin: ageBeginDependant, age_end: ageEndDependant  }});

}
var gridStore<?= $this->panelId; ?> = new Ext.create('Asgard.store.Employeesr');

var form<?=$this->panelId;?> = Ext.create('Asgard.lib.forms.comboOfficesHR', { innerGrid: grid<?=$this->panelId;?> });

var grid<?=$this->panelId;?> = Ext.create('Asgard.lib.grid.employeesr', { 
    store: gridStore<?= $this->panelId; ?>, 
    id: 'grid02<?=$this->panelId;?>',
    isAdmin: <?=$this->isAdmin; ?>
});

var libraryViewport<?=$this->panelId; ?> = Ext.create('Ext.panel.Panel', {
    layout: {
        type: 'vbox',
        align : 'stretch',
        pack  : 'start'
    },
    items: [
        form<?=$this->panelId; ?>,
        grid<?=$this->panelId; ?>
   ]
});
Ext.getCmp('content-panel').getActiveTab().add(libraryViewport<?= $this->panelId; ?>);
</script>
