<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Asgard Information system'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/webapp/menu.css')
            //->prependStylesheet($this->basePath() . '/css/prettyPhoto.css')
            ->prependStylesheet($this->basePath() . '/css/slimbox2.css')
            ->prependStylesheet($this->basePath() . '/css/webapp/general.css')
            ->prependStylesheet($this->basePath() . '/js/extjs/resources/css/ext-all-neptune.css')
         ?>

        <!-- Scripts -->
        <?php 
	      echo $this->headScript()
                    //->prependFile($this->basePath('js/jquery.prettyPhoto.js'))
                      ->prependFile($this->basePath('js/slimbox2.js'))
                      ->prependFile($this->basePath('js/jquery-1.8.3.min.js'))
                      ->prependFile($this->basePath() . '/js/extjs/src/ux/panel/PDF.js')
                      ->prependFile($this->basePath() . '/js/extjs/src/ux/CTemplate.js')
                      ->prependFile($this->basePath() . '/js/extjs/features/FixedSummary.js')
                                      ->prependFile($this->basePath() . '/js/web/app.js')
				      ->prependFile($this->basePath() . '/js/extjs/ext-theme-neptune.js')
				      ->prependFile($this->basePath() . '/js/extjs/ext-all-dev.js')
                                      ->prependFile($this->basePath() . '/js/pdf.js/pdf.js')
				      ->prependFile($this->basePath() . '/js/tinymce/tiny_mce_src.js')
                                      ->prependFile($this->basePath() . '/js/webrootkit.base64.js')


	 ?>
    </head>
    <body>
    <?php echo $this->content; ?>
    </body>
</html>
