<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Asgard Information system'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/webapp/menu.css')
            ->prependStylesheet($this->basePath() . '/css/slimbox2.css')
            ->prependStylesheet($this->basePath() . '/css/webapp/general.css')
            ->prependStylesheet($this->basePath() . '/js/extjs/resources/css/ext-all-neptune.css')
            //->prependStylesheet($this->basePath() . '/js/bootstrap/css/bootstrap-theme.min.css')
            //->prependStylesheet($this->basePath() . '/js/bootstrap/css/bootstrap.min.css')
         ?>

        <!-- Scripts -->
        <?php 
	      echo $this->headScript()
                //->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                //->prependFile($this->basePath() . '/js/bootstrap/js/bootstrap.min.js')
                ->prependFile($this->basePath('js/slimbox2.js'))
                ->prependFile($this->basePath('js/jquery-1.8.3.min.js'))
                ->prependFile($this->basePath() . '/js/extjs/src/ux/panel/PDF.js')
                ->prependFile($this->basePath() . '/js/extjs/src/ux/CTemplate.js')
                ->prependFile($this->basePath() . '/js/extjs/src/ux/CheckCombo.js')
                ->prependFile($this->basePath() . '/js/extjs/features/FixedSummary.js')
                ->prependFile($this->basePath() . '/js/web/app.js')
                ->prependFile($this->basePath() . '/js/extjs/ext-theme-neptune.js')
                ->prependFile($this->basePath() . '/js/extjs/ext-all-dev.js')
                ->prependFile($this->basePath() . '/js/pdf.js/pdf.js')
                ->prependFile($this->basePath() . '/js/pdf.js/compatibility.js')
                ->prependFile($this->basePath() . '/js/tinymce/tiny_mce_src.js')
                ->prependFile($this->basePath() . '/js/webrootkit.base64.js')
                
    	 ?>
        <!-- NEED THIS for Safari Mac to render work -->
        <script type="text/javascript">
            // Specify the main script used to create a new PDF.JS web worker.  
            // In production, change this to point to the combined `pdf.js` file.  
            PDFJS.workerSrc = '<?=$this->basePath();?>/js/pdf.js/pdf.worker.js';  
        </script>
    </head>
    <body>
    <?php echo $this->content; ?>
    </body>
</html>