<?php echo $this->doctype(); ?>
<html>
<head>
  <meta charset="utf-8">
  <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ?>
    <?php
        $appPath = getcwd();
        $url = $appPath . '/public/images/backgrounds/';
        $counter=0;
        foreach (new DirectoryIterator($url) as $fileInfo) {
            if($fileInfo->isDot()) continue;
            $counter++;
            $backgroundFiles[$counter]=$fileInfo->getFilename();
        }
        $idxImage = rand(1, $counter);
    ?>

    <!--  <link rel="stylesheet" type="text/css" href="/js/extjs/resources/css/ext-all.css" /> -->
    <link rel="stylesheet" type="text/css" href="<?=$this->basepath('/js/extjs/resources/css/ext-all-neptune.css'); ?>" />
    <link rel="stylesheet" type="text/css" href="<?=$this->basepath('/css/logindialog/flags.css'); ?>" />
    <link rel="stylesheet" type="text/css" href="<?=$this->basepath('/css/logindialog/IconCombo.css'); ?>" />
    <link rel="stylesheet" type="text/css" href="<?=$this->basepath('/css/logindialog/LoginDialog.css'); ?>" />
    
    <style type='text/css'>
        .x-body {
        	background: url('../images/backgrounds/<?=$backgroundFiles[$idxImage]; ?>');
        	background-repeat:no-repeat;
        	background-size: 100%;
        	background-position:center; 
        	background-attachment:fixed;
        }
    </style>
    
    <script type="text/javascript" src="<?=$this->basepath('/js/jstz.js'); ?>"></script>
    <script type="text/javascript" src="<?=$this->basepath('/js/extjs/ext-all-dev.js'); ?>"></script>
    <script type="text/javascript" src="<?=$this->basepath('/js/web/logindialog/overrides.js'); ?>"></script>
    <script type="text/javascript" src="<?=$this->basepath('/js/web/logindialog/IconCombo.js'); ?>"></script>
    <script type="text/javascript" src="<?=$this->basepath('/js/commons/logindialog/LoginDialogLanguages.js'); ?>"></script>
    <script type="text/javascript" src="<?=$this->basepath('/js/web/logindialog/LoginDialog.js'); ?>"></script>
    <script type="text/javascript" src="<?=$this->basepath('/js/web/logindialog/LoginDialogInit.js'); ?>"></script>
</head>
<body>
</body>
</html>