<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
        <title>Login</title>
        <script src="/js/touch/sencha-touch-all-debug.js" type="text/javascript"></script>
        <script src="/js/commons/logindialog/LoginDialogLanguages.js" type="text/javascript"></script>
        <!-- <script src="/js/mobile/logindialog/LoginDialog.js" type="text/javascript"></script>
        <script src="/js/mobile/logindialog/app.js" type="text/javascript"></script> -->
        <script src="/js/mobile/logindialog/LoginDialog5.js" type="text/javascript"></script>
        <script src="/js/mobile/logindialog/LoginDialogInit.js" type="text/javascript"></script>
        <link href="/js/touch/resources/css/sencha-touch.css" rel="stylesheet" type="text/css" />
    </head>
    <body></body>
</html>