<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'IMS\Module'                        => __DIR__ . '/Module.php',
    'IMS\Controller\IndexController' => __DIR__ . '/src/IMS/Controller/IndexController.php',
    'IMSTest\Framework\TestCase'        => __DIR__ . '/tests/IMS/Framework/TestCase.php',
    'IMSTest\SampleTest'                => __DIR__ . '/tests/IMS/SampleTest.php',
);
