<?php
/**
 * @application Asgard Information System :: asgard-is
 * @version 1.0.0 devel
 * @author Joe Nilson <joenilson@gmail.com>
 */
?>
<style>
    .ims-diagram {
        //overflow: auto;
        height: 100%;
    }
    
    .ims-main-process {
        float: left;
        height: 93%;
        width: 55%;
        position: relative;
    }
    
    .ims-central-body {
        display: block;
        clear: both;
        width: auto;
        height: 50%;
        background-color: #ffcccc;
    }
    
    .ims-measure-dispatch {
        float: right;
        background-color: #00538d;
        width: 15%;
        text-align: center;
    }
    
    .ims-request {
        float: left;
        background-color: #387038;
        width: 15%;
        text-align: center;
    }
    
    .ims-satisfaction {
        float: right;
        width: 15%;
        text-align: center;
    }
    
    .ims-strategic-process {
        display: block;
        clear: both;
        width: auto;
        height: 25%;
        position: relative;
    }
    
    .ims-support-process {
        display: block;
        clear: both;
        width: auto;
        height: 25%;
        position: relative;
    }
    
    .ims-add-link {
        text-decoration: none;
        color: yellow;
        border: thin yellow dashed;
        background-color: black;
        padding: 1px 3px 1px 3px;
        float: right;
        bottom: auto;
        position:absolute;
        bottom:0;
        right:0;
    }
</style>
<script>
var diagram<?=$this->panelId; ?>;




var toolsProcess = [{
            type: 'plus',
            tooltip: 'Add Process',
            handler: fnTool
        },{
            type: 'minus',
            tooltip: 'Remove Process',
            handler: fnTool
        }];

var strategicProcess = Ext.create('Ext.panel.Panel',{
    title: 'Strategic Processes',
    renderTo: 'ims-strategic-process',
    name: 'ims-strategic-process',
    layout: 'fit',
    tools: toolsProcess
});

var mainProcess = Ext.create('Ext.panel.Panel',{
    title: 'Main Processes',
    renderTo: 'ims-main-process',
    name: 'ims-main-process',
    layout: 'fit',
    tools: toolsProcess
});

var supportProcess = Ext.create('Ext.panel.Panel',{
    title: 'Support Processes',
    renderTo: 'ims-support-process',
    name: 'ims-support-process',
    layout: 'fit',
    tools: toolsProcess
});


var storeProcessMain<?=$this->panelId; ?> = Ext.create('Asgard.store.ProcessMain');

storeProcessMain<?=$this->panelId; ?>.load();
storeProcessMain<?=$this->panelId; ?>.filter('assignment','U');


var processList<?=$this->panelId; ?> = Ext.create('Ext.grid.Panel',{
    //layout: 'fit',
    autoScroll: true,
    //flex: 1,
    border: false,
    //plain: false,
    width: '100%',
    height: '100%',
    selType: 'checkboxmodel',
    store: storeProcessMain<?=$this->panelId; ?>,
    columns: {
        items: [
        {text: 'id', flex: 0.25, dataIndex: 'id', sortable: true },
        {text: 'description', flex: 0.75, dataIndex: 'value', sortable: true, tdCls: 'wrapText' }
        ]
    }
    
});


var processWindow<?=$this->panelId; ?> = Ext.create('Ext.window.Window', {
    title: 'Process List',
    closeAction: 'hide',
    width: '280px',
    height: '50%',
    layout: 'fit',
    modal: true,
    items: [ processList<?=$this->panelId; ?> ],
    buttons: [
        '->',
        { 
            text: 'Add',
            handler: fnSubmit
        },
        { 
            text: 'Cancel', 
            handler: fnCancel 
        }
    ]
});


function fnSubmit (button, object)
{
    var grid = processList<?=$this->panelId; ?>;
    var sm = grid.getSelectionModel();
    var m = sm.getSelection();
    
    this.selectedIds = [];
    Ext.each(m, function(rec) {
        this.selectedIds.push(rec.get("id"));
    }, this);
    
    var actionType = Ext.get('toolType').value;
    var processType = Ext.get('processType').value;
    console.log(this.selectedIds);
    
    Ext.Ajax.request({
        url: 'ims/processdiagram',
        params: {
            type: actionType,
            process: processType,
            values: Ext.encode(this.selectedIds),
            module: 'diagram'
        },
        success: function(response){
            var text = response.responseText;
            // process server response here
        }
    });
    
}

function fnCancel ()
{
    processWindow<?=$this->panelId; ?>.hide();
}

function fnTool(me, e, object, tool) {
    var panel = tool.up('panel');

    //formProcess<?=$this->panelId; ?>.addParam({ type_process : panel.name });
    
    Ext.get('toolType').value=tool.type;
    Ext.get('processType').value=panel.name;
    
    //console.log(Ext.get('toolType'));//.setValue(tool.name);
    //console.log(Ext.get('processType'));//.setValue(panel.name);
    
    if (processWindow<?=$this->panelId; ?>.isVisible()) {
        processWindow<?=$this->panelId; ?>.hide();
    } else {
        processWindow<?=$this->panelId; ?>.show();
    }
    
    //console.log(panel.name);
}

/*
Ext.get('add-strategic-process').on('click', function() {
    if (processWindows<?=$this->panelId; ?>.isVisible()) {
        processWindows<?=$this->panelId; ?>.hide();
    } else {
        processWindows<?=$this->panelId; ?>.show();
    }
});
*/
   
</script>
<div class='ims-diagram'>
    <div class='ims-strategic-process' id='ims-strategic-process'>
    </div>
    <div class="ims-central-body">
        <div class='ims-request'>Requisitos</div>
        <div class='ims-main-process' id='ims-main-process'>
        </div>
        <div class="ims-satisfaction">Satisfacción</div>
        <div class='ims-measure-dispatch'>Medicion / Entrega</div>
    </div>
    <div class="ims-support-process" id='ims-support-process'>
    </div>
</div>
<input type="hidden" id="toolType">
<input type="hidden" id="processType">