<?php
/**
 * @application Asgard Information System :: asgard-is
 * @version 1.0.0 devel
 * @author Joe Nilson <joenilson@gmail.com>
 */
?>
<script>
<?php
/*
if(!empty($this->userRole)){
    $var=str_replace(' ','',$this->userRole);
    echo "var toolbarType".$this->panelId." = Ext.create('Asgard.lib.gridToolbar".$var."',{titleBarText: '<b>".$this->HiraGridTitle."</b>'});\n";
}
*/
?>
/**
* Custom function used for column renderer
* @param {Object} val
*/
/*
function riskleveler(val, meta) {
    if (val < 9 && val > 0) {
        meta.tdCls = 'red-column';
    } else if (val < 16 && val > 8) {
        meta.tdCls = 'yellow-column';
    } else if (val > 15) {
        meta.tdCls = 'green-column';
    }
    return val;
}
*/
var <?php echo 'rowEditing'.$this->panelId; ?> = Ext.create('Ext.grid.plugin.RowEditing', {
    clicksToMoveEditor: 1,
    autoCancel: false
});

function deployCombos(comboField,comboValue){
    var combo = formDataRequest<?=$this->panelId;?>.getForm().findField(comboField);
    var store = combo.store;
    store.on("load", function(store, records, state, operation, opts) {
            combo.setValue(comboValue);
    });
}

var HIRAStore<?=$this->panelId; ?> = Ext.create('Asgard.store.HiraDocuments');
<?php 
//echo 'HIRAStore'.$this->panelId.'.load();'; 
?>

var formDataRequest<?=$this->panelId; ?> = Ext.create('Asgard.lib.forms.comboCCL',{
    region: 'north'
});

var HIRAGridPanel<?=$this->panelId; ?> = Ext.create('Asgard.lib.grid.hira_general',{
    store: HIRAStore<?=$this->panelId; ?>,
    region: 'center'
});
/*
var <?php echo 'HIRAGridPanel'.$this->panelId; ?> = Ext.create('Asgard.lib.GridPanel', {
  autoShow: true,
  autoDestroy: true,
  autoScroll: true,
  border: false,
  frame: false,
  region: 'center',
  layout: 'fit',
  flex: 0.90,
  selType: 'checkboxmodel',
  store: <?php echo 'HIRAStore'.$this->panelId; ?>,
  dockedItems: [{
    xtype: toolbarType<?php echo $this->panelId; ?>
  }],
  tools: [{
    type: 'expand',
    tooltip: 'Upload Master File',
    handler: fnLibraryTool
  }],
  columns: {
      plugins: [{
            ptype: 'gridautoresizer'
            
        }
    ],
      items: [
            {text: "Id", flex:0.25, sortable: true, dataIndex: 'id_danger_risk', hidden: true },
            {text: "<?=$this->HiraGridHeaderTypeProcess; ?>", flex:1, sortable: true, filter: 'combo', dataIndex: 'type_desc', tdCls: 'wrapText'},
            {text: "<?=$this->HiraGridHeaderProcess; ?>", flex:1, sortable: true, filter: 'combo', dataIndex: 'process_sup_desc', tdCls: 'wrapText'},
            {text: "<?=$this->HiraGridHeaderSubProcess; ?>", flex:1.3, sortable: true, filter: 'combo', dataIndex: 'process_main_desc', tdCls: 'wrapText'},
            {text: "<?=$this->HiraGridHeaderDangerDesc; ?>", flex:1.5, sortable: true, filter: 'combo', dataIndex: 'desc_danger', tdCls: 'wrapText'},
            {text: "<?=$this->HiraGridHeaderRiskDesc; ?>", flex:1.2, sortable: true, filter: true, dataIndex: 'desc_risk', tdCls: 'wrapText'},
            {text: "<?=$this->HiraGridHeaderHiraEval; ?>",
            columns: [{
                    text     : '<?=$this->HiraGridHeaderScaleHigh; ?>',
                    width    : 50,
                    sortable : true,
                    filter: true,
                    dataIndex: 'eval_iper_h',
                    align: 'center',
                    renderer : riskleveler,
                    editor : { xtype: 'numberfield', allowBlank: false, minValue: 0, maxValue: 25,
                        hideTrigger: true, keyNavEnabled: false, mouseWheelEnabled: false
                    }
                }, {
                    text     : '<?=$this->HiraGridHeaderScaleMedium; ?>',
                    width    : 50,
                    sortable : true,
                    filter: true,
                    renderer :  riskleveler,
                    align: 'center',
                    dataIndex: 'eval_iper_m',
                    editor : { xtype: 'numberfield', allowBlank: false, minValue: 0, maxValue: 25,
                        hideTrigger: true, keyNavEnabled: false, mouseWheelEnabled: false
                    }
                }, {
                    text     : '<?=$this->HiraGridHeaderScaleLow; ?>',
                    width    : 50,
                    sortable : true,
                    align: 'center',
                    filter: true,
                    renderer : riskleveler,
                    dataIndex: 'eval_iper_l',
                    editor : { xtype: 'numberfield', allowBlank: false, minValue: 0, maxValue: 25,
                        hideTrigger: true, keyNavEnabled: false, mouseWheelEnabled: false
                    }
                }]
            },
            {text: "<?=$this->HiraGridHeaderMeasures; ?>", flex:1.2, sortable: true, filter: true, dataIndex: 'control_measures', 
                editor: {
                    xtype: 'textareafield', allowBlank: false
                },
                tdCls: 'wrapText'
            },
            {text: "<?=$this->HiraGridHeaderResidualRiskEval; ?>",
            columns: [{
                    text     : '<?=$this->HiraGridHeaderScaleHigh; ?>',
                    width    : 50,
                    sortable : true, 
                    filter: true,
                    align: 'center',
                    dataIndex: 'eval_risk_h',
                    renderer : riskleveler,
                    editor : { xtype: 'numberfield', allowBlank: false, minValue: 0, maxValue: 25,
                        hideTrigger: true, keyNavEnabled: false, mouseWheelEnabled: false
                    }
                }, {
                    text     : '<?=$this->HiraGridHeaderScaleMedium; ?>',
                    width    : 50,
                    sortable : true, 
                    filter: true,
                    align: 'center',
                    renderer : riskleveler,
                    dataIndex: 'eval_risk_m',
                    editor : { xtype: 'numberfield', allowBlank: false, minValue: 0, maxValue: 25,
                        hideTrigger: true, keyNavEnabled: false, mouseWheelEnabled: false
                    }
                }, {
                    text     : '<?=$this->HiraGridHeaderScaleLow; ?>',
                    width    : 50,
                    sortable : true, 
                    filter: true,
                    align: 'center',
                    renderer : riskleveler,
                    dataIndex: 'eval_risk_l',
                    editor : { xtype: 'numberfield', allowBlank: false, minValue: 0, maxValue: 25,
                        hideTrigger: true, keyNavEnabled: false, mouseWheelEnabled: false
                    }
                }]
            }
        ]
    },
});
*/
<?php
/*
if ($this->userRole!='Viewer'){
    echo 'rowEditing'.$this->panelId.".init(HIRAGridPanel".$this->panelId.");\n\r";
    echo "HIRAGridPanel".$this->panelId.".plugins.push(rowEditing".$this->panelId.");\n\r";
}
 * */
 ?>
    
function fnCCLProcess(button, opt, obj) {
    var values = button.up('form').getForm().getValues();
    var companies = values['companiesCombo'];
    var countries = values['countriesCombo'];
    var locations = values['locationsCombo'];
    HIRAStore<?= $this->panelId; ?>.load({ params: { module: 'hira', company: companies, country: countries, location: locations}});

}

var HiraSpecs<?=$this->panelId; ?> = Ext.create('Ext.Panel', {
    collapsible: true,
    frame: false,
    region: 'south',
    titleAlign: 'right',
    collapsed: true,
    title: '<?php echo $this->titleHiraSpecs; ?>',
    loader: {
        url: 'ims/hiraspecs/<?php echo $this->moduleId; ?>',
        autoLoad: true,
        scripts: true
    }
});

var <?php echo 'HiraPanel'.$this->panelId; ?> = Ext.create('Ext.Panel', {
    frame: false,
    layout: 'border',
    items: [ 
        HiraSpecs<?=$this->panelId; ?>,
        formDataRequest<?=$this->panelId; ?>,
        HIRAGridPanel<?=$this->panelId; ?>
    ]
});

deployCombos('companiesCombo','<?=$this->companyId;?>');
deployCombos('countriesCombo','<?=$this->countryId;?>');
deployCombos('locationsCombo','<?=$this->locationId;?>');


Ext.getCmp('content-panel').getActiveTab().add(<?php echo 'HiraPanel'.$this->panelId; ?>);
</script>