<script>
//Ext = top.Ext;
Asgard = top.Asgard;

Ext.Loader.setConfig({ 
  enabled: true, 
  paths   : {
    Asgard : '/js/web/app'
  }
});
<?php
if(!empty($this->role)){
  $var=str_replace(' ','',$this->role);
  echo "Ext.require('Asgard.view.content.{$var}Functions');\n";
  echo "var panelContent = '".$this->panelContent."';\n";
  echo "var toolbarType = '".$var."-functions';\n";
}
?>
Ext.tip.QuickTipManager.init();
/*
Ext.create('Ext.panel.Panel', {
    scope: this,
    bodyPadding: 15,  // Don't want content to crunch against the borders
    width: 300,
    title: 'Filters',
    items: [{
	//text: 'One',
        xtype: 'datefield',
        fieldLabel: 'Start date'
    }, {
        
        xtype: 'textfield',
        fieldLabel: 'End date'
    }],
    renderTo: document.body
});
*/
Ext.create('Ext.form.Panel', {
  //title: 'Results',
  bodyPadding: 15,
  //width: 600,
  //height: 400,
  renderTo: document.body,
  docketItems: {
    xtype: toolbarType,
  },
  /*
  dockedItems: {
   xtype: 'toolbar',
    dock: 'top',
    ui: 'header',
    items: [
    {
      text: 'Save',
      frame: false,
    }, 
    '->',
    {
      text: 'Dont Save',
      frame: false,
    },]
  },
  */
  defaults: {
    layout: 'fit',
    border: true,
    frame: false,    
  },
  items: [{               // Results grid specified as a config object with an xtype of 'grid'
      xtype: 'container',
      //flex: 1,
      html: panelContent// Use 1/3 of Container's height (hint to Box layout)
  }],
});

</script>