<script>
<?php
if(!empty($this->role)){
  $var=str_replace(' ','',$this->role);
  echo "Ext.require('Asgard.lib.toolbar{$var}');\n";
  echo "var panelContent = '".$this->panelContent."';\n";
  //echo "var panelContent = '';\n";
  echo "var toolbarType = '".$var."-toolbar';\n";
}
?>
Ext.tip.QuickTipManager.init();

var Panel = Ext.create('Asgard.lib.RTFPanel', {
  dockedItems: {
    xtype: toolbarType
  },
  submit: '#',
  autoShow: true,
  autoDestroy: true,
  frame: false,
  layout: 'fit',
  //renderTo: 'contentModule-<?php echo $this->contentId; ?>',
  items: [{
      xtype: 'container',
      anchor: '100%',
      html: panelContent
  }],
  
});

function onClick(btn){
    //console.log(btn);
    switch (btn.text){
        case "Search":
            console.log('Search lib class to be implemented.');
            break;
        case "Refresh":
            console.log('Refresh lib class to be implemented.');
            break;
        case "Edit Content":
            console.log('Editor lib class to be implemented.');
            console.log(Panel.items);
            Panel.removeAll();
            var items = [{ xtype: 'rtfeditor', value: panelContent, autoHeight: true }];
            Panel.add(items);
            //Panel.items.items[0].update("Changed by click!");;
            Panel.doLayout();
            break;
        case "Add Content":
            console.log('Add lib class to be implemented.');
            break;
        case "Remove Content":
            console.log('Remove lib class to be implemented.');
            break;
        case "Save Changes":
            console.log('Save lib class to be implemented.');
            break;
        default:
            console.log('At this point we will do nothing.');
            break;
    }
}
Ext.getCmp('content-panel').getActiveTab().add(Panel);
</script>
<div id='contentModule-<?php echo $this->contentId; ?>'></div>
    