<?php
/**
 * @application Asgard Information System :: asgard-is
 * @version 1.0.0 devel
 * @author Joe Nilson <joenilson@gmail.com>
 */
?>
<style>

</style>
<script>
    function riskleveler(val, meta) {
        if (val > 2 ) {
            meta.tdCls = 'red-column';
        } else if (val == 2) {
            meta.tdCls = 'yellow-column';
        } else if (val == 1) {
            meta.tdCls = 'green-column';
        } else if (val == 0 || val == null){
            return "";
        }
        return val;
     }
    
    function fnSummaryRender(value)
    {
        var formatedValue =  (value  == 0 || value == null ) ? "":value;
        //return Ext.String.format("<span style=\'float:right;\'>{0}</span>",formatedValue);
        return formatedValue;
    }

/*
 * 
 * Dynamic Model to Incidents List Store
 */
Ext.define('Asgard.model.HiraIncidentsList<?php echo $this->panelId; ?>', {
    extend: 'Ext.data.Model',
    fields: [
        'date_incident',
        <?php
        foreach($this->listIT as $values ){
            echo "{name: '".$values->id_incident."', type: 'int' },";
        }
        ?>
        {name: 'summaryIncidents', type: 'int' }
    ]
});

/*
 * Store to get the List of Incident registered
 */
var <?php echo 'HIRAStoreIL' . $this->panelId; ?> = Ext.create('Asgard.store.HiraIncidentsList',{
    model: 'Asgard.model.HiraIncidentsList<?php echo $this->panelId; ?>'
});

 /*
 * Grid to show the Incidents List
 */

var <?php echo 'HIRAGridIL' . $this->panelId; ?> = Ext.create('Asgard.lib.GridPanel', {
    autoScroll: true,
    border: false,
    plain: false,
    width: '100%',
    features: [{
        ftype: 'fixedsummary',
    }],
    fixedsummarytips : true,
    flex: 1,
    title: 'Lista de Incidentes',
    store: <?php echo 'HIRAStoreIL' . $this->panelId; ?>,
    tools: [{
        type: 'plus',
        tooltip: 'Add Incident',
        handler: fnLibraryTool
    }],
    columns: {
            /*
            plugins: [{
                ptype: 'gridautoresizer'
            }],
            */
        items: [
            {text: "Fecha", flex: 3, sortable: true, dataIndex: 'date_incident', align: 'center', filter: false, //format:'Y-m-d', 
                fixedSummaryRenderer: function(){ return "<b>Incidentes</b>"; }},
            <?php
            foreach($this->listIT as $values ){
                echo "{text: \"T{$values->id_incident}\", flex: 1, sortable: true, renderer :  riskleveler, dataIndex:'{$values->id_incident}', align: 'right', filter: false, "
                ."fixedSummaryType: 'sum', fixedSummaryRenderer: riskleveler"
                ."},\n";
            }
            ?>
            {text: "Total Incidentes Dia", flex: 2, sortable: true, dataIndex: 'summaryIncidents', renderer: riskleveler, align: 'right', filter: false, 
                fixedSummaryType: 'sum', fixedSummaryRenderer: riskleveler 
            }
        ]
    }
});

function fnLibraryTool(action,mark,form,tool){
    console.log(form);
    console.log(tool);
    if(tool.type==='plus'){
        winAdd = Ext.create('Asgard.lib.window.windowGeneric',{
            height: document.documentElement.clientHeight - 50,
            innerPanel : HIRAGridIL<?=$this->panelId; ?>
        });
        winAdd.add(Ext.create('Asgard.lib.forms.hiraNewIncident'));
        //console.log('mostramos la ventana para agregar un incidente');
        winAdd.show();
    }
}
  
        HIRAGridIL<?=$this->panelId; ?>.on('itemdblclick', function(me, record){
            //call window to show list of incidents
            grid = me.up('panel');
            panel = grid.up('panel');
            form = panel.items.getAt(0).getForm();
            var companiesValue = form.findField('companiesCombo').getValue();
            var countriesValue = form.findField('countriesCombo').getValue();
            var locationsValue = form.findField('locationsCombo').getValue();
            var dateValue = record.data.date_incident;
            var detailsGrid = Ext.create('Asgard.lib.grid.hira_incidents_details');
            detailsGrid.getStore().load({params: {'company': companiesValue,'country': countriesValue, 'location': locationsValue, 'date_incident': dateValue}});
            windowDetails<?php echo $this->panelId; ?>.add(detailsGrid);
            windowDetails<?php echo $this->panelId; ?>.show();
        });


/*
 * Window Details to display Grid Incidents' Details
 */
var windowDetails<?php echo $this->panelId; ?> = Ext.create('Asgard.lib.hiraIncidentsDetails', {
    layout: 'fit',
    title: 'Details',
    closeAction: 'hide',
    height: '450px',
    width: '80%'
});

function deployCombos(form,comboField,comboValue){
    var combo = form.getForm().findField(comboField);
    var store = combo.store;
    store.on("load", function(store, records, state, operation, opts) {
            combo.setValue(comboValue);
    });
}

function fnCCLDProcess(button, opt, obj) {
    var values = button.up('form').getForm().getValues();
    var companies = values['companiesCombo'];
    var countries = values['countriesCombo'];
    var locations = values['locationsCombo'];
    var monthfield = values['monthfield'];
    HIRAStoreIL<?= $this->panelId; ?>.load({params: {'companies': companies,'countries': countries, 'locations': locations, 'monthfield': monthfield}});
}

var formHiraIL<?=$this->panelId;?> = Ext.create('Asgard.lib.forms.comboCCLD', { width: '100%',innerGrid: HIRAGridIL<?=$this->panelId;?> });

deployCombos(formHiraIL<?=$this->panelId;?>,'companiesCombo','<?=$this->companyId;?>');
deployCombos(formHiraIL<?=$this->panelId;?>,'countriesCombo','<?=$this->countryId;?>');
deployCombos(formHiraIL<?=$this->panelId;?>,'locationsCombo','<?=$this->locationId;?>');

    /*
     * Viewport to show the Incidents Type and the Incidents List
     */
    var viewportHiraIL<?=$this->panelId; ?> = Ext.create('Ext.Panel', {
        title: 'Analisis de Incidentes',
        layout: {
            type: 'border',
            padding: 0
        },
        items: [
            new Ext.create('Asgard.lib.grid.hira_incidents_type'),
            {
                region: 'center',
                layout: 'vbox',
                flex: 0.8,
                items: [
                    formHiraIL<?=$this->panelId;?>,
                    HIRAGridIL<?=$this->panelId;?>
                    
                ]
            },
        ]
    });
    Ext.getCmp('content-panel').getActiveTab().add(viewportHiraIL<?=$this->panelId;?>);
</script>