<?php
/**
 * @application Asgard Information System :: asgard-is
 * @version 1.0.0 devel
 * @author Joe Nilson <joenilson@gmail.com>
 */
?>
<script>
/*
 * Store to get the List of Countries
 */
var <?php echo 'CountriesStore'.$this->panelId; ?> = Ext.create('Asgard.store.Countries');
<?php echo 'CountriesStore'.$this->panelId.'.load();'; ?>

/*
 * Store to get the List of Locations
 */
var <?php echo 'LocationsStore'.$this->panelId; ?> = Ext.create('Asgard.store.Locations');

/*
 * Store to get the List of Incidents Type
 */
var <?php echo 'HIRAStoreIT'.$this->panelId; ?> = Ext.create('Asgard.store.HiraIncidentsType');
<?php echo 'HIRAStoreIT'.$this->panelId.'.load();'; ?>
/*
 * Store to get the List of Incident registered
 */
var <?php echo 'HIRAStoreIL'.$this->panelId; ?> = Ext.create('Asgard.store.HiraIncidentsList');

/*
 * Grid to show the Store HIRAStoreIT
 */
var <?php echo 'HIRAGridIT'.$this->panelId; ?> = Ext.create('Asgard.lib.GridPanel', {
  autoShow: true,
  autoDestroy: true,
  autoScroll: true,
  border: false,
  frame: false,
  flex: 0.2,
  //selType: 'checkboxmodel',
  store: <?php echo 'HIRAStoreIT'.$this->panelId; ?>,
  columns: {
      plugins: [{
            ptype: 'gridautoresizer'
            
        }
    ],
      items: [
            {text: "Id", flex:0.25, sortable: true, dataIndex: 'id_incident', filter: true },
            {text: "Description", flex:0.75, sortable: true, filter: 'combo', dataIndex: 'val_incident', tdCls: 'wrapText'},
        ]
    }
});


/*
 * 
 */
var <?php echo 'CountriesCombo'.$this->panelId; ?> = Ext.create('Ext.form.ComboBox', {
    fieldLabel: 'Pais',
    store: <?php echo 'CountriesStore'.$this->panelId; ?>,
    queryMode: 'local',
    displayField: 'name',
    valueField: 'id',
    anchor: '50%',
    forceSelection: true,
    emptyText: 'No values at this time',
    listeners: {
        select: function(combo,records,opts) {
            console.log(combo.getValue('id'));
            
            <?php echo 'LocationsStore'.$this->panelId; ?>.load({params:{cid: combo.getValue('id')}});
        }    
    }    
});

var <?php echo 'LocationsCombo'.$this->panelId; ?> = Ext.create('Ext.form.ComboBox', {
    fieldLabel: 'Ubicación',
    store: <?php echo 'LocationsStore'.$this->panelId; ?>,
    queryMode: 'local',
    forceSelection: true,
    displayField: 'location_name',
    valueField: 'id',
    anchor: '25%',
    emptyText: 'No values at this time',
});

/*
 * Form Panel to attach
 */
var <?php echo 'formHiraIL'.$this->panelId; ?> = Ext.create ('Ext.form.Panel',{
    border: false,
    plain: false,
    width: '100%',
    fieldDefaults: {
        labelAlign: 'top',
        msgTarget: 'side'
    },
    bodyStyle: 'padding:5px 5px 5px',
    defaults: {
        border: false,
        xtype: 'panel',
        flex: 1,
        layout: 'anchor'
    },
    layout: 'hbox',
    items: [
            <?php echo 'CountriesCombo'.$this->panelId; ?>,
            <?php echo 'LocationsCombo'.$this->panelId; ?>,,
            {xtype: 'monthfield', submitFormat: 'Y-m-d', fieldLabel: 'Mes y Año', format: 'F, Y', anchor: '25%'}
    ],
    buttons: ['->', {
        text: 'Consultar'
    }]
});


/*
 * Viewport to show the Incidents Type and the Incidents List
*/
var <?php echo 'viewportHiraIL'.$this->panelId; ?> = Ext.create('Ext.Panel',{
   title: 'Listado',
   layout: 'hbox',
   items: [
       <?php echo 'HIRAGridIT'.$this->panelId; ?>,
       {
            layout: 'vbox',
            flex: 0.8,
            items: [
                    <?php echo 'formHiraIL'.$this->panelId; ?>,
                   //{html: 'dos<br />dos<br />dos<br />dos<br />', xtype:'container', flex: 1},
                   {html: 'tres<br />tres<br />tres<br />tres<br />tres<br />tres<br />', xtype:'container', flex: 1}
        
            ]
       },
   ]
});
Ext.getCmp('content-panel').getActiveTab().add(<?php echo 'viewportHiraIL'.$this->panelId; ?>);
</script>