<?php
/* 
 * Copyright (C) 2014 Joe Nilson <joenilson at gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<script>
function deployCombos(comboField,comboValue){
    var combo = form<?=$this->panelId;?>.getForm().findField(comboField);
    var store = combo.store;
    store.on("load", function(store, records, state, operation, opts) {
            combo.setValue(comboValue);
    });
}

function <?=$this->typeDocFunction;?>(button, opt, obj) {
    var values = button.up('form').getForm().getValues();
    var companies = values['companiesCombo'];
    var countries = values['countriesCombo'];
    var locations = values['locationsCombo'];
    var process_id = values['processCombo'];
    var year = values['yearsCombo'];
    var monthyear = values['monthfield'];
    
    viewStore<?=$this->panelId;?>.load({ params: { module: 'master', typedoc: '<?=$this->typeDoc;?>', company: companies, country: countries, location: locations, process: process_id, years: year, month: monthyear }});
}

var viewStore<?= $this->panelId; ?> = new Ext.create('Asgard.store.ObjDocuments');

var view<?=$this->panelId;?> = Ext.create('Asgard.lib.dataview.objdocument', { 
    store: viewStore<?= $this->panelId; ?>
});
   
var form<?=$this->panelId;?> = Ext.create('Asgard.lib.forms.<?=$this->typeDocCombo;?>', { innerPanel: view<?=$this->panelId;?> });

var content<?=$this->panelId; ?> = Ext.create('Asgard.lib.Panels.ObjDocumentPanel',{
    items: view<?=$this->panelId;?>,
    typeDoc: '<?=$this->typeDoc;?>'
});

deployCombos('companiesCombo','<?=$this->companyId;?>');
deployCombos('countriesCombo','<?=$this->countryId;?>');
deployCombos('locationsCombo','<?=$this->locationId;?>');

var libraryViewport<?=$this->panelId; ?> = Ext.create('Ext.panel.Panel', {
    layout: {
        type: 'vbox',
        align : 'stretch',
        pack  : 'start'
    },
    items: [
        form<?=$this->panelId; ?>,
        content<?=$this->panelId; ?>
   ]
});
Ext.getCmp('content-panel').getActiveTab().add(libraryViewport<?= $this->panelId; ?>);
</script>