<?php

/*
 * Copyright (C) 2013 Joe Nilson <joenilson@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * @application Asgard Information System :: asgard-is
 * @version 1.0.0 devel
 * @author Joe Nilson <joenilson@gmail.com>
 */
?>
<script>
var DocumentsStore<?=$this->threadId; ?> = Ext.create('Asgard.store.Companies');
    DocumentsStore<?=$this->threadId; ?>.load();
    
var DocumentsGrid<?=$this->threadId; ?> = Ext.create('Asgard.lib.GridPanel', {
    autoShow: true,
    autoDestroy: true,
    autoScroll: true,
    border: false,
    frame: false,
    //region: 'west',
    collapsible: true,
    //flex: 0.2,
    title: 'Documentos Asociados',
    store: DocumentsStore<?=$this->threadId; ?>,
    columns: {
        plugins: [{
                ptype: 'gridautoresizer'
            }],
        items: [
            {text: "Id", flex: 0.1, sortable: true, dataIndex: 'id', filter: true},
            {text: "Document", flex: 0.9, sortable: true, filter: true, dataIndex: 'comercial_name', tdCls: 'wrapText'},
            {xtype: 'actioncolumn',width: 30,sortable: false,menuDisabled: true,
                items: [
                {
                    icon: 'images/default/16x16/view.png',
                    tooltip: 'View File',
                    scope: this,
                    handler: showDocument
                }]
            }
        ]
    }
});    

    
var tabpanel<?=$this->threadId; ?> = Ext.create('Ext.tab.Panel', {
    items: [
        {
            title: 'Detalles',
            bodyPadding: 5,
            layout: {
                type: 'vbox',
                pack: 'start',
                align: 'stretch'
            },
            defaults: {
                frame: false,
                padding: 2
            },
            items: [{
                title: 'Misión',
                flex: 1,
                margin: '0 0 5 0',
                html: '<?=$this->threadData[0]->mission; ?>'
            }, {
                title: 'Dueño del proceso',
                flex: 1,
                margin: '0 0 5 0',
                html: '<?=$this->owner; ?>'
            }, {
                title: 'Alcance',
                flex: 2,
                html: '<?=$this->threadData[0]->scope; ?>'
            },{
                layout: {
                    type: 'hbox',
                    pack: 'start',
                    align: 'stretch'
                }, 
                items: [{
                    title: 'Entradas',
                    flex: 1,
                    margin: '0 5 0 0',
                    html: 'Entradas'
                },{
                    title: 'Salidas',
                    flex: 1,
                    html: 'Salidas'
                }]
            }]
        },{
            title: 'Actividades',
            html: 'Details will be added here'
        },
        DocumentsGrid<?=$this->threadId; ?>,
        /*
        {
            title: 'Documentos Asociados',
            html: 'Listado de Documentos'
        },
        */
        {
            title: 'IPER',
            html: 'IPER Will be here'
        },{
            title: 'Aspectos Ambientales',
            html: 'Hello world 2'
        },{
            title: 'Indicadores',
            html: 'Hello world 3'
        }]
});

var windowDoc = Ext.create('Ext.window.Window',{
    title: 'Document Viewer',
    closable: true
});


function showDocument(obj, id, component, icon, event, record){
    var document = Ext.create('Ext.ux.panel.PDF', {
        width    : 450,
        height   : 500,
        pageScale: 1,                                           // Initial scaling of the PDF. 1 = 100%
        src      : 'http://cdn.mozilla.net/pdfjs/tracemonkey.pdf', // URL to the PDF - Same Domain or Server with CORS Support
    });
    windowDoc.add(document);
    windowDoc.show();
    /*
    console.log(obj);
    console.log(id);
    console.log(component);
    console.log(icon);
    console.log(event);
    console.log(record);
    */
}

Ext.getCmp('content-panel').getActiveTab().getComponent(0).getComponent(2).add(tabpanel<?=$this->threadId; ?>);
</script>

