<script>
var revision_date = Ext.Date.format(Ext.Date.parse("<?php echo $this->presentationContentApproved; ?>", "Y-m-d g:i:s.u"), "l, jS F Y");

var windowPresentation = Ext.create('Asgard.view.window.systemInformation', {
    companyNameField: {
        value: '<? echo $this->companyName; ?>',
    },
    defaultModuleField: {
        value: '<? echo $this->defaultModule." - ".$this->presentationContentHeader; ?>'
    },
    presentationContentHeaderField: {
        value: '<? echo $this->presentationContentHeader; ?>'
    },
    presentationContentReviewField: {
        value: '<? echo $this->presentationContentReview; ?>'
    },
    presentationContentApprovedField: {
        value: revision_date
    }

});
Ext.getCmp('content-panel').getActiveTab().add(windowPresentation);
</script>